### ISSUE TITLE
AD5860 hardware test

### ISSUE THREAD

**Issue by paulvee** [RobTillaart/AD5680#2] opened 2023-09-19 14:52 UTC
Hi Rob,

Very fast again, wow!
I won't have time tomorrow, but I'll start to test it out on Thursday and get back with results.
Many thanks,
Paul

**Comment by RobTillaart** [comment] 2023-09-19 18:06
@paulvee 
I'm going to merge so I can register in the library manager.
That allows other people to test and generate feedback etc.

**Comment by RobTillaart** [comment] 2023-09-22 14:54
@paulvee 

My email is overloaded and it is hard to keep your messages separate. 
(GitHub is better suited for discussions)

I understand
- the library works but not correctly
  - there is a factor 16  error, 
  - probably some bit shift error
- there is an issue with an OPAMP and a gain factor.

Given the time the library was written and not tested on my site I am not unsatisfied so far. 
Will go through the code and datasheet to see if I can find that factor 16.
If so I will create a develop branch with improved code.

**Comment by RobTillaart** [comment] 2023-09-22 15:28
@paulvee 

Found two points.
- code has SPI_MODE1 which should be SPI_MODE0  (datasheet states falling edge)

Datasheet page 12.
_Data from the DIN line is clocked into the 24-bit shift register on the falling edge of SCLK._

From Arduino.cc
![image](https://github.com/RobTillaart/AD5680/assets/462844/f77a9885-3612-4439-b65c-d1b4c5ebe6c0)


The function **updateDevice()** did an incorrect mask on the lowest 2 bits.    0xF0 ==> 0xFC
```uint8_t c = (value << 2)  & 0xFC;  //  bit 00-05```

development branch is in progress.

----

Question: did you test the SW SPI interface or the HW SPI?

**Comment by RobTillaart** [comment] 2023-09-22 15:43
![image](https://github.com/RobTillaart/AD5680/assets/462844/a9d51835-ff96-472d-abfc-316c7aab29b1)

Here you also see the falling edge of the clock is the moment the DIN  is read 
(or better when the CLOCK is LOW, the DIN may change)

**Comment by RobTillaart** [comment] 2023-09-22 19:16
@paulvee 
Added a triangle wave example to the develop branch.

**Comment by paulvee** [comment] 2023-09-23 09:10
Rob, here is something fishy going on with the SPI interface.
I'm using your latest code with SPI_MODE0. With that selected, the device no longer outputs something.
When I force a transmit of a=b=c=0x0, there are three data bytes (a, b, c) that get sampled, see attached.

Above is the MOSI, below is the CLK
![DS2_20230923094430](https://github.com/RobTillaart/AD5680/assets/3100354/0a3fac18-15d6-47b4-8dc7-a4da2227d135)

When I send c=2 I get this in detail for the third byte:
![DS2_20230923095801](https://github.com/RobTillaart/AD5680/assets/3100354/0d6d8911-3c51-48da-896f-ade8556c4387)

It seems that clocking on the rising edge would be better.

**Comment by paulvee** [comment] 2023-09-23 09:49
Continuing...
Setting the SPI_MODE back to 0, the device seems to work again.
However, when I send out the maximum for 18 bits (0->3FFFF), something weird happens.
![DS2_20230923102714](https://github.com/RobTillaart/AD5680/assets/3100354/793913b6-3439-4d0a-a987-a37bc8c616a1)
Yellow trace is the MISO, blue is the output of the device.
You can see that the output of the device is already ramping-up to VCC during the transmission of 0-3FFFF. During the transmission, the device seems to restart several times.

When I lower the maximum to 3FFFF/16, you get a picture of what you would expect to see:
![DS2_20230923103542](https://github.com/RobTillaart/AD5680/assets/3100354/1400f815-91a7-4c40-89c8-a0ba7c8c9486)
I've been struggling for two days with this now but can't figure it out yet.

**Comment by paulvee** [comment] 2023-09-23 09:56
Here are the essentials of the code I'm running:
```

uint32_t max = (pow(2,18)-1)/16; // maximum resolution at 18 bits

void loop()
{
  for (uint32_t i = 1; i < max; i++)
  {
     AD16_HW.setValue(i);
  }
  AD16_HW.setValue(0); // back to zero
  delay(1000);
}
```

**Comment by RobTillaart** [comment] 2023-09-23 10:53
I'm in several other projects now (renovation living room et al)
If the device us 18 bit, dividing by 16 makes you loose 4 bits. That just does not make sense.
1. Can you check the type of the chip itself? Just to be sure 
2. Can you give SWSPI a try as that can be controlled in more detail.
3. Di you have pull ups (4k) in the clock and data line?

**Comment by paulvee** [comment] 2023-09-23 12:21
Take your time... I have the answer...

(2) I switched to SWSPI, and (3) I added the pull_ups (made no real difference)
Just to see what got sent to the device, I forced a value of 0x31111 to be transmitted.
![DS2_20230923123029](https://github.com/RobTillaart/AD5680/assets/3100354/78c30daf-fac0-4e51-938a-a2ab445744cf)

Here is the first byte (a) in more detail:
![DS2_20230923123135](https://github.com/RobTillaart/AD5680/assets/3100354/1b097fef-90e2-4a1a-9526-038c36cff7ef)
The first two bits are the 'x' for bit 0 and 1, then you see the '1' of the first byte.
And here is the last byte (c):
![DS2_20230923123148](https://github.com/RobTillaart/AD5680/assets/3100354/172ed2a3-4e6d-4387-90df-642306bfa2ec)
The last 4 bits are the 'x' for bit 23 and 22 and the two reserved bits 21 and 20 and then the '3' of the last Byte.
This all seems to be OK as far as I can tell so the chip get's what it needs.

But...
(1) While looking at the markings on the chip I noticed an anomaly. It didn't match the markings of the datasheet.
I ordered the parts from TME, and I got two in a plastic container hand-marked AD5680. When I verified the invoice, they have a different chip marked down as I ordered. Apperantly, I got the DAC8531. The markings on the chip match the datasheet. 

It has exactly the same pin-out but is a 16-bit DAC. It also has a 24-bit data input, but not left-shifted by 2. That and the two extra bits explains the x16 issue for me.

I guess that solves the problem I was having. 
Unfortunately, TME does no longer carry the AD5680 so I can't get one soon. I'll contact them anyway.
It looks like I'm stuck with the 16-bit chip and have to depart from this library project for now.

I'm sorry for muddying the waters for you.
The good news is that you can continue with your remodeling project and score some points.

**Comment by RobTillaart** [comment] 2023-09-23 12:45
That explains a lot (but still there was an error in the bits) 

SW SPI provides better pictures, it is a bit slower but that is an advantage sometimes.

> DAC8531

Explains all I guess,  it has 24 bits too but the meaning of the first byte is different, so that might explain some
strange graphs when sending numbers above 65535.

Q:  if you proceed with this chip, you could check my DAC8551 library. 
That has a DAC8531 derived class. You can give it a try.

> The good news is that you can continue with your remodeling project and score some points.

We're in the last phase, did all the walls, ceiling, windows, doors, today the floor and then it should be good for another 10 years or more I hope.

**Comment by paulvee** [comment] 2023-09-23 12:52
With some minor changes I could make this library work for the DAC8531.
I learned a lot from you in this process.
I'll also check out your DAC8551 library and see if I can contribute.

![DS2_20230923133816](https://github.com/RobTillaart/AD5680/assets/3100354/af1060f1-a2c9-4382-90cd-17a820b47bc0)

PS I noticed that the SWSPI is about 23x slower than the HWSPI that I am using again now.

Thank you & best regards,
Paul

**Comment by RobTillaart** [comment] 2023-09-23 13:05
> PS I noticed that the SWSPI is about 23x slower than the HWSPI that I am using again now.

Mainly caused by slow digitalWrite(). If you optimize port and bit registers the SW SPI can become pretty fast.
An ESP32 on 240 MHz is almost on PAR as the SW SPI does not do transactions.

If you can do a test with that DAC8551 library, would be great. 
Confirmation that things work as intended are useful for a library developer like me

**Comment by paulvee** [comment] 2023-09-23 13:14
Hi Rob,
I installed and tried the DAC8551 library on an Arduino Nano with the DAC8531 invocation, and it works right out of the box. (does not surprise me)
I was looking at a way to add some comments to that library, but could not figure it out. (I'm not that good with Github) So here it is.

The result of the DAC8551_hw_spi.ino, with the following change:
`DAC8531 mydac(8); // CLK=D13, MISO=D11, SS = D8`
And here is a screenshot of the output:
![DS2_20230923135944](https://github.com/RobTillaart/AD5680/assets/3100354/20aba5ce-12b0-4edf-92da-b71e36c5a0a8)

**Comment by RobTillaart** [comment] 2023-09-23 13:54
Thanks,
Nice sine wave !
 I will create a DAC8531 specific example (with your settings) and add the image to it.

**Comment by RobTillaart** [comment] 2023-09-23 14:09
Created a develop branch - https://github.com/RobTillaart/DAC8551/tree/develop 
will be merged today/tomorrow

**Comment by RobTillaart** [comment] 2023-09-24 18:06
@paulvee 

I close this issue for now. Feel fee to reopen it when needed. 
Will merge the 0.1.1 develop branch tonight.

**Closed as completed by RobTillaart** 2023-09-24 18:06 UTC
Labels: good first issue
